// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/product/getDetails.ts";
import * as $1 from "./routes/api/product/getProduct.ts";
import * as $2 from "./routes/api/product/searchList.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/product/[slug].tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Products.tsx";
import * as $$2 from "./islands/SearchList.tsx";

const manifest = {
  routes: {
    "./routes/api/product/getDetails.ts": $0,
    "./routes/api/product/getProduct.ts": $1,
    "./routes/api/product/searchList.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/product/[slug].tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Products.tsx": $$1,
    "./islands/SearchList.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
